jobs:
    job:
        runs-on: ubuntu-22.04
        steps:
            -   names: send_message
            -   run: |
                curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" 
                -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" 
                -d "text=你好"
