name: Send "Hello" via Telegram

# 触发条件：即使
on: [push]

jobs:
  send-message:
    runs-on: ubuntu-22.04
    steps:
      - name: 更新消息
        # 使用curl调用Telegram Bot API 更新消息
        run: curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getUpdates" 