name: Send "Hello" via Telegram

# 触发条件：即使
on: [push]

jobs:
  send-message:
    runs-on: ubuntu-22.04
    steps:
      - name: Send "Hello" to specific user
        # 使用curl调用Telegram Bot API发送消息
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=你好"